##if (serviceType != 'Job')
LykkeServiceService:
  Db:
    LogsConnString:
      settings-key: LykkeServiceService-LogsConnString
      types:
        - AzureTableStorage
##endif
##if (serviceType != 'Job' && aztrepos)
    AzureDbConnString:
      settings-key: LykkeServiceService-AzureDbConnString
      types:
        - AzureTableStorage
##endif
##if (serviceType != 'Job' && mssqlrepos)
    SqlDbConnString:
      settings-key: LykkeServiceService-SqlDbConnString
##endif
##if (serviceType != 'Service')
LykkeServiceJob:
  Db:
    LogsConnString:
      settings-key: LykkeServiceJob-LogsConnString
      types:
        - AzureTableStorage
##endif
##if (serviceType != 'Service' && aztrepos)
    AzureDbConnString:
      settings-key: LykkeServiceJob-AzureDbConnString
      types:
        - AzureTableStorage
##endif
##if (serviceType != 'Service' && mssqlrepos)
    SqlDbConnString:
      settings-key: LykkeServiceJob-SqlDbConnString
##endif
##if (azurequeuesub)
  AzureQueue:
    ConnectionString:
      settings-key: ConnectionString
      types:
        - AzureTableStorage
##endif
##if (rabbitsub || rabbitpub)
  Rabbit:
##endif
##if (rabbitpub)
    Publishers:
      ConnectionString:
        settings-key: Pub-ConnectionString
        types:
          - RabbitMq
##endif
##if (rabbitsub)
    Subscribers:
      ConnectionString:
        settings-key: Sub-ConnectionString
        types:
          - RabbitMq
##endif
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

